# Generated by Django 4.2.30 on 2026-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_variants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'طلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة (Pending)'), ('accepted', 'تم القبول (Accepted)'), ('preparing', 'جاري التجهيز (Preparing)'), ('on-delivery', 'جاري التوصيل (On Delivery)'), ('delivered', 'تم التسليم (Delivered)'), ('canceled', 'ملغى (Canceled)')], default='pending', max_length=50),
        ),
    ]
